version: '2'

services:
  postgres:
    image: postgres:10-alpine
    ports:
      - 5430:5432

  app:
    build: .
    command: "/bin/sh -c 'while true; do sleep 60; done'"
    volumes:
      - .:/app
    ports:
      - 3000:3000
    depends_on:
      - postgres
