version: '2'

services:
  postgres:
    image: postgres:10-alpine
    ports:
      - 5454:5432

  app:
    build: .
    command: "/bin/sh -c 'while true; do sleep 60; done'"
    volumes:
      - .:/app
      - $HOME/.ssh/id_rsa:/root/.ssh/id_rsa:ro
      - $HOME/.ssh/id_rsa.pub:/root/.ssh/id_rsa.pub:ro
    ports:
      - 5000:5000
    environment:
      SERVER_PORT: 5000
      DB_PORT: 5432
      DB_HOST: postgres
    depends_on:
      - postgres
